title: Summit Productions
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://summitproductions.ml
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#e60000"
  systems:
    - name: Website
      category: Website
      link: https://summitproductions.ml
    - name: API
      category: Website
    - name: Backup
      category: Website
    - name: Game Services
      category: Main Servers
    - name: Matchmaking
      category: Main Servers
    - name: Friends Parties & Messaging
      category: Main Servers
    - name: Stats & Leaderboards
      category: Main Servers
    - name: Item Shop
      category: Main Servers
    - name: Game Services
      category: Testing Servers
    - name: Matchmaking
      category: Testing Servers
    - name: Friends, Parties & Messaging
      category: Testing Servers
    - name: Stats & Leaderboards
      category: Testing Servers
    - name: Item Shop
      category: Testing Servers
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#0a0c0f"
  enableLastMod: true
  headerTextColor: white
  logo: /img/favicon-32x32.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: false
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Website
      closed: false
    - name: Main Servers
      closed: false
    - name: Testing Servers
      closed: false
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  enableCustomHTML: true
  useLargeHeaderDesign: false
